version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/postgres/data
    volumes:
      - test_db_volume:/var/postgres/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"


volumes:
  test_db_volume: